services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-5.1.2
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORTS=8181/tcp,8181/udp
      - UMASK=002
    volumes:
      - ${DATADIR}/qbittorrent/config:/config
      - ${DATADIR}/library/torrents:/data/torrents
    ports:
      - 8181:8181
      - 6881:6881
      - 6881:6881/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN_NAME}`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.tls.certresolver=myclouddns
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8181
      - traefik.http.routers.qbittorrent.middlewares=crowdsec-bouncer@docker,authelia-forwardauth@docker,geoblock@file
      - homepage.group=Other
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://qbittorrent.${DOMAIN_NAME}/
      - homepage.description=qBittorrent web client
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://qbittorrent:8181
      - homepage.widget.username=${QBIT_USER}
      - homepage.widget.password=${QBIT_PASS}
      - homepage.widget.enableLeechProgress=true
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true