services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.2@sha256:163f3384db6cba9f68eaa83ca5f4209298b6029ba2d07b5e67562d0715baf5b9
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8181
      - UMASK=002
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${DATADIR}/qbittorrent/config:/config
      - ${DATADIR}/library/torrents:/data/torrents
    ports:
      - 8181:8181
      - 6881:6881
      - 6881:6881/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN_NAME}`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.tls.certresolver=myclouddns
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8181
      - traefik.http.routers.qbittorrent.middlewares=geoblock@file,crowdsec-bouncer@docker,authelia-forwardauth@docker
      - homepage.group=Servarr
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://qbittorrent.${DOMAIN_NAME}/
      - homepage.description=qBittorrent web client
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://qbittorrent:8181
      - homepage.widget.username=${QBIT_USER}
      - homepage.widget.password=${QBIT_PASS}
      - homepage.widget.enableLeechProgress=true
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true
