version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"           # where your docker-compose.yml is
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Jerusalem"
    commit-message:
      prefix: "deps(compose)"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
