services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest@sha256:bc53b40b13c8b2a84e9b93c21f65fcd7d574b741014fb93912eb9efd93015aa2
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    read_only: true
    cap_drop:
      - all
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_DNS_API_TOKEN}
      - DOMAINS=nullflix.uk,*.nullflix.uk,wg.nullflix.uk
      - IP6_PROVIDER=none
    restart: unless-stopped
