services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest@sha256:5e61736b982b87d84a1120b4767c4deff0f2cc55ca3ee9dcb1dc58623039b5cb
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    read_only: true
    cap_drop:
      - all
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_DNS_API_TOKEN}
      - DOMAINS=nullflix.uk,*.nullflix.uk,wg.nullflix.uk
      - IP6_PROVIDER=none
    restart: unless-stopped
