services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:15.1.0
    restart: unless-stopped
    environment:
      - INSECURE=true
      # - WG_HOST=${FQDN}
      # - PASSWORD_HASH=${WIREGUARD_HASHED_PASSWORD}
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_DEFAULT_DNS="${LOCAL_IP}"
      # - WG_MTU="1412"
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg-easy.rule=Host(`wg-easy.${DOMAIN_NAME}`)
      - traefik.http.routers.wg-easy.entrypoints=websecure
      - traefik.http.routers.wg-easy.tls=true
      - traefik.http.routers.wg-easy.tls.certresolver=myclouddns
      - traefik.http.services.wg-easy.loadbalancer.server.port=51821
      - traefik.http.routers.wg-easy.middlewares=geoblock@file,crowdsec-bouncer@docker,authelia-forwardauth@docker
      - homepage.group=Other
      - homepage.name=WG-Easy
      - homepage.icon=wireguard.png
      - homepage.href=http://wg-easy.${DOMAIN_NAME}/
      - homepage.description=Fast and secure VPN protocol
      - homepage.widget.type=wgeasy
      - homepage.widget.url=http://wg-easy:51821
      - homepage.widget.version=2
      - homepage.widget.username=${WIREGUARD_USERNAME}
      - homepage.widget.password=${WIREGUARD_PASSWORD}
    volumes:
      - ${DATADIR}/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      # - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
    networks:
      - internal

networks:
  internal:
    external: true