services:
  sablier:
    image: sablierapp/sablier:1.16.1@sha256:4137043766568f4254d30e6c970918bdb522a2213af8ddee4a379f95673510b6
    container_name: sablier
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE}
      - PROVIDER_NAME=docker
      - STRATEGY_DYNAMIC_SHOW_DETAILES_BY_DEFAULT=true
      - PROVIDER_DOCKER_STRATEGY=stop
    networks:
      - internal

networks:
  internal:
    external: true

