services:
  sablier:
    image: sablierapp/sablier:1.18.0@sha256:c00c8a01c8c809dd258a8b362ad8ba9a9227753fc9857ae7506fd427175e038c
    container_name: sablier
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE}
      - PROVIDER_NAME=docker
      - STRATEGY_DYNAMIC_SHOW_DETAILES_BY_DEFAULT=true
      - PROVIDER_DOCKER_STRATEGY=stop
    networks:
      - internal

networks:
  internal:
    external: true

