services:
  sablier:
    image: sablierapp/sablier:1.15.0@sha256:c706adda00f977667b049b2973297129e9eda943f07817c85969fc55e73bb26b
    container_name: sablier
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE}
      - PROVIDER_NAME=docker
      - STRATEGY_DYNAMIC_SHOW_DETAILES_BY_DEFAULT=true
      - PROVIDER_DOCKER_STRATEGY=stop
    networks:
      - internal

networks:
  internal:
    external: true

