services:
  prefetcharr:
    image: phueber/prefetcharr:latest@sha256:dceb95a3fa822e8673eccd3acd6dd73baa111c8cab48cd6f6a5a876fde9c47d6
    container_name: prefetcharr
    volumes:
      # Copy prefetcharr.toml to your ${DATADIR} and set the api keys for jellyfin and sonarr
      - ${DATADIR}/prefetcharr/prefetcharr.toml:/config
      - ${DATADIR}/prefetcharr/log:/log
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true
