services:
  prefetcharr:
    image: phueber/prefetcharr:latest@sha256:4912a3b0e63afa01ead3c1dd20efa35d6ace3d0dbce4883a28a25a2219fa299e
    container_name: prefetcharr
    volumes:
      # Copy prefetcharr.toml to your ${DATADIR} and set the api keys for jellyfin and sonarr
      - ${DATADIR}/prefetcharr/prefetcharr.toml:/config
      - ${DATADIR}/prefetcharr/log:/log
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true
