theme: auto

server:
  address: "tcp://0.0.0.0:9091"
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderProxyAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
      auth-request:
        implementation: 'AuthRequest'

session:
  name: authelia_session
  secret: '{{ mustEnv "SESSION_SECRET" }}'
  expiration: 8h
  inactivity: 30m
  remember_me: 30d
  cookies:
    - domain: '{{ mustEnv "DOMAIN_NAME" }}'
      authelia_url: 'https://auth.{{ mustEnv "DOMAIN_NAME" }}'
      same_site: lax

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: '{{ mustEnv "STORAGE_ENCRYPTION_KEY" }}'

identity_validation:
  reset_password:
    jwt_secret: '{{ mustEnv "JWT_SECRET" }}'

authentication_backend:
  file:
    path: /config/users.yaml
    password:
      algorithm: argon2

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

access_control:
  default_policy: deny
  rules:
    # Jellyfin: Uses plugin for authentication, bypass forward-auth
    - domain: 'jellyfin.{{ mustEnv "DOMAIN_NAME" }}'
      policy: bypass

    - domain: 'jellyseerr.{{ mustEnv "DOMAIN_NAME" }}'
      policy: bypass
    
    # Protect all other subdomains with authentication
    - domain: '*.{{ mustEnv "DOMAIN_NAME" }}'
      policy: one_factor
    
    # Example: Override specific domain with different policy
    # Uncomment and modify as needed:
    # - domain: 'admin.{{ mustEnv "DOMAIN_NAME" }}'
    #   policy: two_factor  # Require 2FA for admin panel
    #
    # - domain: 'public.{{ mustEnv "DOMAIN_NAME" }}'
    #   policy: bypass  # No authentication needed
    #
    # - domain: 'sensitive.{{ mustEnv "DOMAIN_NAME" }}'
    #   policy: two_factor
    #   subject:
    #     - "group:admins"  # Only admins can access

notifier:
  # Uncomment this if you want to use the filesystem notifier
  # filesystem:
    # filename: /config/notification.txt
  disable_startup_check: true
  smtp:
    address: 'smtp.gmail.com:587'
    username: '{{ mustEnv "SMTP_USERNAME" }}'
    password: '{{ mustEnv "SMTP_PASSWORD" }}'
    sender: '{{ mustEnv "SMTP_USERNAME" }}'
    subject: "[Authelia] {title}"
    startup_check_address: '{{ mustEnv "SMTP_USERNAME" }}'
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false
    tls:
      server_name: 'smtp.gmail.com'
      skip_verify: false
      minimum_version: TLS1.2