services:
  gh-runner:
    build:
      context: /home/servarr/pirateduck/homeserver/runner
      dockerfile: Dockerfile
    container_name: gh-runner
    restart: unless-stopped
    user: root
    environment:
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      REPO_URL: ${REPO_URL}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_ALLOW_RUNASROOT: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/servarr/pirateduck/homeserver/_work:/_work
    entrypoint: [ "bash", "-lc",
      "./config.sh \
        --url ${REPO_URL} \
        --token ${RUNNER_TOKEN} \
        --name ${RUNNER_NAME:-local-docker} \
        --labels self-hosted,docker \
        --work _work \
        --unattended --replace \
      && ./run.sh"
    ]
