name: Auto-merge Dependabot (minor/patch)

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Guard - only direct dependencies
        if: ${{ steps.meta.outputs['dependency-type'] != 'direct' }}
        run: echo "Not a direct dependency update. Skipping." && exit 0

      - name: Auto-approve minor/patch
        if: ${{ contains(fromJson('["version-update:semver-minor","version-update:semver-patch"]'), steps.meta.outputs['update-type']) }}
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          review-message: "Auto-approve Dependabot minor/patch"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_AUTOMERGE }}

      - name: Merge when checks pass
        if: ${{ contains(fromJson('["version-update:semver-minor","version-update:semver-patch"]'), steps.meta.outputs['update-type']) }}
        uses: peter-evans/auto-merge@v4
        with:
          token: ${{ secrets.PAT_AUTOMERGE }}
          merge-method: squash
